### ISSUE TITLE
Remove isVisible from PostImage IntersectionObserver disonnection logic

### ISSUE THREAD

**Issue by alshakero** [alshakerM/my-instagram#92]
See https://github.com/alshakerM/my-instagram/blob/master/components/PostImage/PostImage.js#L19

**Comment by alshakerM** [comment]
On it.

**Comment by alshakero** [comment]
Closing as done in https://github.com/alshakerM/my-instagram/commit/a16e9a53a216bdcae5b367fc25a49ba85323c62b
